### ISSUE TITLE
How to hide title and description

### ISSUE THREAD

**Issue by neha275** [ZacharyKhan/ZKCarousel#42]
I don't want to add title and description, if empty string sent then black shadow coming how to hide

![Screenshot 2021-09-07 at 9 46 55 PM](https://user-images.githubusercontent.com/26864742/132378168-080f33ef-5f1b-4f79-8e2f-1b9f2781859f.png)

**Comment by ZacharyKhan** [comment]
Hello @neha275, one option would be to update ZKCarousel to accept _any_ `UICollectionViewCell` rather than only accepting the single cell that's currently displayed. Another option would be to create a protocol, and define ZKCarousel to accept any conformer of this protocol.

I'll look into this later this evening when I have some time and push an update. Thanks for the suggestion.

**Comment by ZacharyKhan** [comment]
I've made some updates to the library, run `pod update` to receive them. Keep in mind, I did not remove the gradient. If you just wish to add an image, that's basically a UICollectionView that displays UICollectionViewCells with a single image view. 

I would encourage you to take inspiration from this library, fork it and modify it to fit your specific needs.
